import 'package:pvoil_station/common/resource/keylanguage_resource/key_language.dart';

const Map<String, String> en = {
  // datetime
  KeyLanguage.mon: 'Mon',
  KeyLanguage.tue: 'Tue',
  KeyLanguage.wed: 'Wed',
  KeyLanguage.thu: 'Thu',
  KeyLanguage.fri: 'Fri',
  KeyLanguage.sat: 'Sat',
  KeyLanguage.sun: 'Sun',
  KeyLanguage.month: 'Month',
  KeyLanguage.year: 'Year',
  KeyLanguage.device: 'Devices',
  KeyLanguage.login: 'Login',
  KeyLanguage.fingerprint_dialog: 'Scan Fingerprint To Enter Vault',
  KeyLanguage.noBiometric: 'noBiometric',
  KeyLanguage.noAccount: "Don't have an account? ",
  KeyLanguage.unmanaged_device: 'Unmanaged devices',
  KeyLanguage.connect_time: 'Connect time',
  // account
  KeyLanguage.doSignUpAccount: 'Do you account?',
  KeyLanguage.signUp: 'Register',
  KeyLanguage.signAccountSuccess:
      'Successful account registration. Please login again to continue using!',
  KeyLanguage.forgotPassword: 'Forgot password?',
  KeyLanguage.password_old_fail: 'The current password is incorrect!',
  KeyLanguage.exit_app: 'Do you sure want to exit?',
  KeyLanguage.sendOtpAgain: 'Send OTP again in: ',
  KeyLanguage.exp_login:
      'You have reached the end of your login session. Please log in again!',
  // account screen
  KeyLanguage.avatar_name: 'Girl',
  KeyLanguage.confirmPwd: 'Confirm password',
  // action
  KeyLanguage.onback: 'Back',
  KeyLanguage.add: 'Add',
  KeyLanguage.apply: 'Apply',
  KeyLanguage.send_request: 'Send request',
  KeyLanguage.exit: 'Cancel',
  KeyLanguage.resume: 'Next',
  // status
  KeyLanguage.success: 'Success',
  KeyLanguage.nodata: 'No data',
  KeyLanguage.repeat: 'Repeat',
  KeyLanguage.assign_connection:
      'Automatically assign a new connection to the group',
  KeyLanguage.new_connection: 'Request an approval upon new connection',
  // widget wifi
  KeyLanguage.encode: 'Encode',
  KeyLanguage.wifi_name: 'Wifi name (SSID)',
  KeyLanguage.set_device_name: 'Device name',
  KeyLanguage.device_info: 'Device Information',
  KeyLanguage.scan_in_network: 'Scan in network',
  KeyLanguage.application_initialization: 'Application initialization',
  KeyLanguage.device_connecting: 'Device connecting',
  KeyLanguage.network_scanning: 'Network scanning',
  KeyLanguage.wi_fi_configuration: 'Wi-Fi Configuration',
  KeyLanguage.advanced_option: 'Advanced option',
  KeyLanguage.frequency: 'Frequency',
  KeyLanguage.network_bandwidth: 'Bandwidth',
  KeyLanguage.hind_wifi: 'Hind Wifi',
  KeyLanguage.access_permission: 'Permission to use',
  KeyLanguage.collapse: 'Collapse',
  KeyLanguage.device_code: 'Device code',
  // widget menu
  KeyLanguage.manager: 'Manager',
  KeyLanguage.unlimit: 'UnManager',
  KeyLanguage.connecting: 'Connected',
  KeyLanguage.newMemberEquipment: 'New Member Equiqment:',
  KeyLanguage.block: 'Block',
  KeyLanguage.function: 'Function',
  KeyLanguage.connect_time_full: 'Time connected',
  KeyLanguage.not_empty: 'You cannot leave this field blank',
  KeyLanguage.adult: 'Mode: ADULTS',
  KeyLanguage.child: 'Mode: CHILDREN',
  KeyLanguage.mode_use: 'Usage mode',
  KeyLanguage.use_manager_advand: 'Additional management',
  KeyLanguage.use_manager: 'User management',
  KeyLanguage.use_manager_mode: 'Management mode',
  KeyLanguage.limit: 'Limit',
  KeyLanguage.monitor: 'Monitor',
  KeyLanguage.change_user_manager: 'Change Manager',
  KeyLanguage.all: 'All',
  KeyLanguage.group: 'Group',
  KeyLanguage.app_a_web: 'Apps and web',
  KeyLanguage.deny: 'Deny',
  KeyLanguage.wifi_type: 'Wifi type',
  KeyLanguage.hello: 'Hello,',
  KeyLanguage.notme: 'Not me',
  // dialog
  KeyLanguage.search_use_app: 'Search Application',
  KeyLanguage.input_search_use_app: 'Search',
  KeyLanguage.no_find_use_appp: 'No find application',
  KeyLanguage.no_find_group_use_appp: 'No find group application',
  KeyLanguage.use_app: 'applications',
  KeyLanguage.filter_use_app: 'Find',
  KeyLanguage.selected: 'Selected',
  KeyLanguage.search_group_use_app: 'Search Group Application',
  KeyLanguage.input_search_group_use_app: 'Search group',
  KeyLanguage.update: 'Update',
  KeyLanguage.enterPhoneNumber: 'Enter Phone Number',
  KeyLanguage.version: 'Software version',
  KeyLanguage.use_service: 'The service is being built',
  KeyLanguage.detail_info: 'Details',
  KeyLanguage.device_type: 'Device type:',
  KeyLanguage.soft_update: 'Software update',
  KeyLanguage.upgrade: 'Upgrade',
  KeyLanguage.re_new: 'Renew',
  KeyLanguage.info_connect: 'Contact infomation',
  KeyLanguage.device_name: 'Device name:',
  KeyLanguage.updatePwdSuccess: 'Password successfully changed',
  KeyLanguage.managed_device: 'Managed device',
  KeyLanguage.device_config: 'Device configuration',
  KeyLanguage.app_config: 'Application Configuration',
  KeyLanguage.config_notify: 'Notification configuration',
  KeyLanguage.config_time: 'Time configuration',
  KeyLanguage.app_security: 'Device security',
  KeyLanguage.pause: 'Pause',
  KeyLanguage.auto_shell: 'Auto Protection',
  KeyLanguage.safe_access: 'Safe Access',
  KeyLanguage.connect_config: 'Connection configuration',
  KeyLanguage.network_config: 'Network configuration',
  KeyLanguage.security_device: 'Device security',
  KeyLanguage.too_short: 'Use at least 8 characters',
  KeyLanguage.updatePwdFail:
      'Password change failed. Please double check the OTP!',
  KeyLanguage.otp_verify_fail:
      'OTP code is incorrect, please check and try again!',
  KeyLanguage.isNotFormatPwd:
      'Password is combine uppercase, lowercase letters, numbers and special characters',
  KeyLanguage.violation_of_the_day: 'Violation of the day',
  KeyLanguage.usage_time: 'Usage time',
  KeyLanguage.total_number_of_devices: 'Total number of devices',
  KeyLanguage.phoneSign: 'Registered phone number',
  KeyLanguage.used: 'Used',
  KeyLanguage.search: 'Search',
  KeyLanguage.otp_verify: 'OTP Verify',
  KeyLanguage.otp_send_notify: 'OTP message has been sent to the phone number',
  KeyLanguage.notPhone: 'Invalid phone number',
  KeyLanguage.isNotEmpty: 'This field is required',
  KeyLanguage.reset_pwd: 'Reset Password',
  KeyLanguage.assetphoneNumber: 'Phone number (*)',
  KeyLanguage.password: 'Password',
  KeyLanguage.assertPwd: 'Password (*)',
  KeyLanguage.assertRepeatPwd: 'Confirm Password (*)',
  KeyLanguage.disconnect: 'Disconnect',
  KeyLanguage.save: 'Save',
  KeyLanguage.signAccount: 'Register Account',
  KeyLanguage.camera: 'Camera',
  KeyLanguage.request_reset_pwd: 'Password reset request',
  KeyLanguage.image_gallery: 'Image Gallery',
  KeyLanguage.phone: 'Phone',
  KeyLanguage.laptop: 'laptop',
  KeyLanguage.desktop: 'Desktop',
  KeyLanguage.tv: 'TV',
  KeyLanguage.device_used: 'Devices in use',
  KeyLanguage.userProfile: 'User profile',
  KeyLanguage.userProfiles: 'User profiles',
  KeyLanguage.timeUsed: 'Time used',
  KeyLanguage.closest_access: 'Accessed',
  KeyLanguage.history: 'History',
  KeyLanguage.setting: 'Setting',
  KeyLanguage.violations: 'Violations',
  KeyLanguage.language_vi: 'Vietnamese',
  KeyLanguage.language_en: 'English',
  KeyLanguage.my_info: 'Personal information',
  KeyLanguage.new_password: 'New password',
  KeyLanguage.renew_password: 'Confirm password',
  KeyLanguage.change_password: 'Change password',
  KeyLanguage.current_password: 'Current password',
  KeyLanguage.language: 'Language',
  KeyLanguage.user_interface: 'User interface',
  KeyLanguage.alert_config: 'Alert configuration',
  KeyLanguage.user_mode_config: 'User mode configuration',
  KeyLanguage.logout: 'Logout',
  KeyLanguage.confirm: 'OK',
  KeyLanguage.cancel: 'Cancel',
  KeyLanguage.notification: 'Notification',
  KeyLanguage.not_received_otp: 'Did not receive OTP? ',
  KeyLanguage.resend_otp: 'Resend OTP',
  KeyLanguage.report: 'Report',
  KeyLanguage.today: 'Today',
  KeyLanguage.yesterday: 'Yesterday',
  KeyLanguage.this_week: 'This week',
  KeyLanguage.last_week: 'Last week',
  KeyLanguage.option: 'Option',
  KeyLanguage.option_high: 'Advanced settings',
  KeyLanguage.condition_use: 'Condition of use',
  KeyLanguage.most_use_app: 'Most used applications',
  KeyLanguage.most_used_users: 'Most used users',
  KeyLanguage.overview: 'Overview',
  KeyLanguage.birthday: 'Birthday',
  KeyLanguage.connect: 'Connect',
  KeyLanguage.full_name: 'Full name',
  KeyLanguage.statistical: 'statistical',
  KeyLanguage.access_manage: 'Access management',
  KeyLanguage.dialogunmanager_success:
      'UnManager device management successfully',
  KeyLanguage.dialogunmanager_fail:
      'Unsuccessful device manager exit, please try again later!',
  KeyLanguage.dialogunmanager: 'Are you sure you want to unmanage this device?',
  KeyLanguage.options: 'optional',
  KeyLanguage.cannot_blank: 'Do not leave this section blank',
  KeyLanguage.password_not_mach: 'Password does not match',
  KeyLanguage.lessSix: 'Field length is too short',
  KeyLanguage.notEmail: 'Email invalidate',
  KeyLanguage.package: 'Package:',
  KeyLanguage.service_usage_time: 'Service usage time:',
  KeyLanguage.activation_date: 'Activation date:',
  KeyLanguage.expiration_date: 'Expiration date:',
  KeyLanguage.extend_package: 'Extend package',
  KeyLanguage.select_the_package: 'Select the package',
  KeyLanguage.we_will_contact_you: 'We will contact you',
  // policies
  KeyLanguage.policies_search_secure: 'Safe search',
  KeyLanguage.policies_secure_child: 'Protect children',
  KeyLanguage.policies_block_web_blacklist: 'Block the dark web',
  KeyLanguage.policies_block_web_phishing: 'Block fake websites',
  KeyLanguage.policies_block_web_gamble: 'Block gambling web',
  KeyLanguage.policies_anti_scam: 'Anti-scam',
  // settings
  KeyLanguage.rate: 'Rate',
  KeyLanguage.ratings: 'Ratings',

  // pvoil transaction create page
  KeyLanguage.create_transaction: 'Create transaction',
  KeyLanguage.payment_banking: 'Payment Banking',
  KeyLanguage.payment_qrcode: 'Payment Qr Code',
  KeyLanguage.next_step: 'Next step',
  KeyLanguage.infomation_user: 'Infomation User',
};
