import 'package:pvoil_station/common/resource/keylanguage_resource/key_language.dart';

const Map<String, String> vi = {
  // datetime
  KeyLanguage.mon: 'T2',
  KeyLanguage.tue: 'T3',
  KeyLanguage.wed: 'T4',
  KeyLanguage.thu: 'T5',
  KeyLanguage.fri: 'T6',
  KeyLanguage.sat: 'T7',
  KeyLanguage.sun: 'CN',
  KeyLanguage.month: 'Tháng',
  KeyLanguage.year: 'Năm',
  // account
  KeyLanguage.login: 'Đăng nhập',
  KeyLanguage.userName: 'Email hoặc số điện thoai',
  KeyLanguage.password: 'Mật khẩu',
  KeyLanguage.forgotPassword: 'Quên mật khẩu?',
  KeyLanguage.confirmPwd: 'Xác nhận lại mật khẩu',
  KeyLanguage.noAccount: 'Bạn chưa có tài khoản? ',
  KeyLanguage.signUp: 'Đăng ký',
  KeyLanguage.doSignUpAccount: 'Chưa có tài khoản?',
  KeyLanguage.sendOtpAgain: 'Gửi lại mã OTP trong: ',
  KeyLanguage.otp_verify_fail:
      'Mã OTP không đúng, vui lòng kiểm tra và thử lại!',
  KeyLanguage.device: 'Thiết bị',
  KeyLanguage.isNotEmpty: 'Trường này bắt buộc phải điền vào',
  KeyLanguage.too_short: 'Sử dụng ít nhất 8 ký tự',
  KeyLanguage.enterPhoneNumber: 'Số điện thoại',
  KeyLanguage.exp_login: 'Bạn đã hết phiên đăng nhập. Vui lòng đăng nhập lại!',
  KeyLanguage.noBiometric:
      'Thiết bị chưa kích hoạt bảo mật bằng TouchID, FaceID Vui lòng kiểm tra lại hoặc đăng nhập bằng mật khẩu ',
  KeyLanguage.unmanaged_device: 'Thiết bị chưa quản lý',
  KeyLanguage.connect_time: 'T.G kết nối',
  KeyLanguage.vn: 'Việt Nam',
  KeyLanguage.uk: 'Vương quốc Anh',
  KeyLanguage.us: 'Hoa kỳ',
  // account screen
  KeyLanguage.avatar_name: 'Con gái',
  KeyLanguage.soft_update: 'Cập nhật phần mềm',
  KeyLanguage.use_service: 'Dịch vụ đang sử dụng',
  KeyLanguage.reset_pwd: 'Reset mật khẩu',
  KeyLanguage.not_received_otp: 'Bạn không nhận được mã OTP? ',
  // action
  KeyLanguage.onback: 'Quay lại',
  KeyLanguage.resend_otp: 'Gửi lại',
  KeyLanguage.apply: 'Áp dụng',
  // status
  KeyLanguage.success: 'Hoàn thành',
  KeyLanguage.nodata: 'Không có dữ liệu',
  //settings
  KeyLanguage.rate: 'Đánh giá',
  KeyLanguage.ratings: 'Lượt đánh giá',

  // widget wifi
  KeyLanguage.wifi_name: 'Tên Wifi (SSID)',
  KeyLanguage.update: 'Cập nhật',
  KeyLanguage.network_config: 'Cấu hình mạng',
  KeyLanguage.scan_in_network: 'Quét trong mạng',
  KeyLanguage.application_initialization: 'Khởi tạo ứng dụng',
  KeyLanguage.device_connecting: 'Kết nối thiết bị',
  KeyLanguage.network_scanning: 'Đang dò quét trong mạng',
  KeyLanguage.wi_fi_configuration: 'Cấu hình wifi',
  KeyLanguage.advanced_option: 'Tuỳ chọn nâng cao',
  KeyLanguage.frequency: 'Tần số',
  KeyLanguage.security_device: 'Bảo mật thiết bị',
  KeyLanguage.connect_config: 'Cấu hình kết nối',
  KeyLanguage.detail_info: 'Thông tin chi tiết',
  KeyLanguage.network_bandwidth: 'Băng thông',
  KeyLanguage.hind_wifi: 'Không hiển thị tên Wifi',
  KeyLanguage.access_permission: 'Cho phép sử dụng',
  KeyLanguage.collapse: 'Thu gọn',
  KeyLanguage.device_code: 'Mã thiết bị',
  KeyLanguage.user_mode_config: 'Cấu hình chế độ người dùng',
  KeyLanguage.encode: 'Mã hoá',
  // widget menu
  KeyLanguage.manager: 'Quản lý',
  KeyLanguage.change_user_manager: 'Chuyển người quản lý',
  KeyLanguage.block: 'Chặn',
  KeyLanguage.function: 'Chức năng',
  KeyLanguage.all: 'Tất cả',
  KeyLanguage.group: 'Nhóm',
  KeyLanguage.app_a_web: 'Ứng dụng & web',
  KeyLanguage.phoneSign: 'Số điện thoại Đăng ký',
  KeyLanguage.upgrade: 'Nâng cấp',
  KeyLanguage.connect: 'Kết nối',
  KeyLanguage.re_new: 'Gia hạn',
  KeyLanguage.info_connect: 'Thông tin liên hệ',
  KeyLanguage.isNotFormatPwd:
      'Mật khẩu kết hợp chứ hoa, chứ thường ,số và ký tự đặc biệt',
  KeyLanguage.add: 'Thêm',
  KeyLanguage.updatePwdFail:
      'Mật khẩu thay đổi không thành công. Vui lòng  kiểm tra lại mã OTP!',
  KeyLanguage.updatePwdSuccess:
      'Mật khẩu thay đổi thành công. Vui lòng đăng nhập lại để tiếp tục sử dụng dịch vụ!',
  KeyLanguage.assetphoneNumber: 'Số điện thoại (*)',
  KeyLanguage.deny: 'Từ chối',
  KeyLanguage.search: 'Tìm kiếm',
  KeyLanguage.managed_device: 'Thiết bị đã quản lý',
  KeyLanguage.otp_verify: 'Xác minh OTP',
  KeyLanguage.otp_send_notify: 'Nhắn OTP đã được gửi tới số điện thoại',
  KeyLanguage.notPhone: 'Số điện thoại không hợp lệ',
  KeyLanguage.request_reset_pwd: 'Yêu cầu reset mật khẩu',
  KeyLanguage.options: 'Tùy chọn',
  KeyLanguage.assertPwd: 'Mật khẩu (*)',
  KeyLanguage.assertRepeatPwd: 'Xác nhận mật khẩu (*)',
  KeyLanguage.pause: 'Tạm dừng',
  KeyLanguage.violation_of_the_day: 'Vi phạm trong ngày',
  KeyLanguage.usage_time: 'Thời lượng sử dụng',
  KeyLanguage.total_number_of_devices: 'Tổng số thiết bị',
  KeyLanguage.used: 'Đã sử dụng',
  KeyLanguage.valueNotEmail: 'Thông tin bạn nhập không phải Email',
  KeyLanguage.assertNoEmpty: "You can't leave this field blank",
  KeyLanguage.askRegister: '',
  KeyLanguage.newMemberEquipment: 'Thiết bị mới của thành viên:',
  KeyLanguage.disconnect: 'Ngắt kết nối',
  KeyLanguage.save: 'Lưu lại',
  KeyLanguage.camera: 'Máy ảnh',
  KeyLanguage.image_gallery: 'Thư viện',
  KeyLanguage.phone: 'Điện thoại',
  KeyLanguage.re_open: 'Mở nhanh tạm thời',
  KeyLanguage.laptop: 'Máy tính bàn',
  KeyLanguage.desktop: 'Máy tính',
  KeyLanguage.tv: 'TV',
  KeyLanguage.device_used: 'Thiết bị sử dụng',
  KeyLanguage.user_mode: 'Chế độ người dùng',
  KeyLanguage.edit_user_mode: 'Sửa chế độ mới',
  KeyLanguage.add_user_mode: 'Thêm chế độ mới',
  KeyLanguage.name_user_mode: 'Tên chế độ',
  KeyLanguage.desc: 'Mô tả',
  KeyLanguage.child_mode: 'Chế độ trẻ em',
  KeyLanguage.child_mode_desc: 'Cấu hình của nhóm đối tượng là trẻ em',
  KeyLanguage.list_u_mode: 'Danh sách chế độ',
  KeyLanguage.input_mode: 'Vui lòng nhập chế độ',
  KeyLanguage.add_new: 'Thêm mới',
  KeyLanguage.userProfile: 'Quản lý Người dùng',
  KeyLanguage.userProfiles: 'Danh sách người dùng',
  KeyLanguage.current_password: 'Mật khẩu hiện tại',
  KeyLanguage.new_password: 'Mật khẩu mới',
  KeyLanguage.renew_password: 'Xác nhận mật khẩu',
  KeyLanguage.timeUsed: 'Thời gian',
  KeyLanguage.closest_access: 'Truy cập gần nhất',
  KeyLanguage.history: 'Nhật ký',
  KeyLanguage.setting: 'Cài đặt',
  KeyLanguage.signAccount: 'Đăng ký tài khoản',
  KeyLanguage.signAccountSuccess:
      'Đăng ký tài khoản thành công. Vui lòng đăng nhập lại để tiếp tục sử dụng!',
  KeyLanguage.accessed: 'Truy cập',
  KeyLanguage.violations: 'Vi phạm',
  KeyLanguage.violationsInday: 'Vi phạm trong ngày',
  KeyLanguage.connecting: 'Đang kết nối',
  KeyLanguage.bandwidth: 'Băng thông hiện tại',
  KeyLanguage.time_use: 'Thời lượng sử dụng',
  KeyLanguage.hour: 'Giờ',
  KeyLanguage.language_vi: 'Tiếng Việt',
  KeyLanguage.lessSix: 'Độ dài trường quá ngắn',
  KeyLanguage.language_en: 'Tiếng Anh',
  KeyLanguage.my_info: 'Thông tin cá nhân',
  KeyLanguage.change_password: 'Đổi mật khẩu',
  KeyLanguage.overview: 'Tổng quan',
  KeyLanguage.language: 'Ngôn ngữ',
  KeyLanguage.notme: 'Không phải tôi',
  KeyLanguage.new_connection: 'Yêu cầu duyệt khi có kết nối mới ',
  KeyLanguage.assign_connection: 'Tự động gán kết nối mới vào nhóm',
  KeyLanguage.user_interface: 'Cấu hình giao diện',
  KeyLanguage.device_info: 'Thông tin thiết bị',
  KeyLanguage.alert_config: 'Cấu hình cảnh báo',
  KeyLanguage.device_config: 'Cấu hình thiết bị',
  KeyLanguage.repeat: 'Nhắc lại',
  KeyLanguage.logout: 'Đăng xuất',
  KeyLanguage.fingerprint_dialog: 'Vui lòng quét vân tay để xác thực đăng nhập',
  KeyLanguage.confirm: 'Xác nhận',
  KeyLanguage.cancel: 'Bỏ qua',
  KeyLanguage.safe_access: 'Truy cập an toàn',
  KeyLanguage.device_name: 'Tên thiết bị:',
  KeyLanguage.device_type: 'Loại thiết bị:',
  KeyLanguage.wifi_type: 'Loại Wifi',
  KeyLanguage.hello: 'Xin chào,',
  KeyLanguage.version: 'Phiên bản phần mềm:',
  KeyLanguage.auto_shell: 'Tự động bảo vệ',
  KeyLanguage.notification: 'Thông báo',
  KeyLanguage.exit_app: 'Bạn có chắc chắn muốn đăng xuất?',
  KeyLanguage.report: 'Báo cáo',
  KeyLanguage.today: 'Hôm nay',
  KeyLanguage.yesterday: 'Hôm qua',
  KeyLanguage.this_week: 'Tuần này',
  KeyLanguage.last_week: 'Tuần trước',
  KeyLanguage.option: 'Tùy chọn',
  KeyLanguage.option_high: 'Tùy chọn nâng cao',
  KeyLanguage.condition_use: 'Tình hình sử dụng',
  KeyLanguage.most_use_app: 'Sử dụng nhiều nhất',
  KeyLanguage.search_use_app: 'Tìm kiếm ứng dụng',
  KeyLanguage.input_search_use_app: 'Nhập tên ứng dụng để tìm kiếm',
  KeyLanguage.no_find_use_appp: 'Không tìm thấy ứng dụng nào',
  KeyLanguage.no_find_group_use_appp: 'Không tìm thấy nhóm ứng dụng nào',
  KeyLanguage.use_app: 'ứng dụng',
  KeyLanguage.filter_use_app: 'Tìm thấy',
  KeyLanguage.selected: 'Đã chọn',
  KeyLanguage.search_group_use_app: 'Tìm kiếmm nhóm ứng dụng',
  KeyLanguage.input_search_group_use_app: 'Nhập tên nhóm để tìm kiếm',
  KeyLanguage.most_used_users: 'Người dùng sử dụng nhiều nhất',
  KeyLanguage.birthday: 'Sinh nhật',
  KeyLanguage.full_name: 'Họ và tên',
  KeyLanguage.statistical: 'Thống kê',
  KeyLanguage.access_manage: 'Quản lý truy cập',
  KeyLanguage.cannot_blank: 'Bạn không được để trống mục này',
  KeyLanguage.password_not_mach: 'Mật khẩu không trùng khớp',
  KeyLanguage.password_old_fail: 'Mật khẩu hiện tại không đúng',
  KeyLanguage.notEmail: 'Email không đúng định dạng',
  KeyLanguage.package: 'Dịch vụ đang dùng:',
  KeyLanguage.service_usage_time: 'Gói dịch vụ:',
  KeyLanguage.activation_date: 'Thời gian kích hoạt:',
  KeyLanguage.expiration_date: 'Thời gian hết hạn:',
  KeyLanguage.extend_package: 'Gia hạn',
  KeyLanguage.select_the_package: 'Lựa chọn gói dịch vụ',
  KeyLanguage.we_will_contact_you: 'Chúng tôi sẽ liên hệ với bạn',
  KeyLanguage.send_request: 'Gửi yêu cầu',
  KeyLanguage.exit: 'Thoát',
  KeyLanguage.resume: 'Tiếp tục',
  KeyLanguage.set_device_name: 'Đặt tên thiết bị',
  KeyLanguage.mode_child: 'Chế độ trẻ em',
  KeyLanguage.mode_child_desc:
      'Bảo vệ an toàn cho trẻ nhỏ trước các nguy cơ trên Internet',
  KeyLanguage.mode_adult: 'Chế độ người lớn',
  KeyLanguage.mode_adult_desc:
      'Bảo vệ an toàn trong mọi giao dịch hàng ngày của bạn',
  KeyLanguage.hint_profile_name: 'Tên người dùng',
  KeyLanguage.profile_mode: 'Chế độ người dùng',
  KeyLanguage.connect_time_full: 'Thời gian kết nối',
  KeyLanguage.not_empty: 'Bạn không được để trống mục này',
  KeyLanguage.adult: 'Chế độ: NGƯỜI LỚN',
  KeyLanguage.child: 'Chế độ: TRẺ EM',
  KeyLanguage.internet_manager: 'Quản lý sử dụng internet',
  KeyLanguage.using: 'Đang sử dụng',
  KeyLanguage.mode_use: 'Chế độ sử dụng',
  KeyLanguage.use_manager: 'Quản lý sử dụng',
  KeyLanguage.use_manager_advand: 'Quản lý bổ sung',
  KeyLanguage.use_manager_mode: 'Chế độ quản lý',
  KeyLanguage.version_info: 'Thông tin phiên bản',
  KeyLanguage.app_config: 'Cấu hình ứng dụng',
  KeyLanguage.config_notify: 'Cấu hình thông báo',
  KeyLanguage.config_time: 'Cấu hình thời gian',
  KeyLanguage.app_security: 'Bảo mật thiết bị',
  KeyLanguage.biometric: 'Bảo mật sinh trắc học',
  KeyLanguage.limit: 'Không cho phép',
  KeyLanguage.unlimit: 'Không quản lý',
  KeyLanguage.dialogunmanager_success: 'Bỏ quản lý thiết bị thành công',
  KeyLanguage.dialogunmanager_fail:
      'Bỏ quản lý thiết bị không thành thành công, vui lòng thử lại sau!',
  KeyLanguage.dialogunmanager:
      'Bạn có chắc chắn muốn bỏ quản lý thiết bị này không?',
  KeyLanguage.monitor: 'Giám sát',
  KeyLanguage.config_time_use: 'Đặt thời gian sử dụng',
  KeyLanguage.ask_sure_delete: 'Bạn có chắc chắn muốn xóa thời gian',
  KeyLanguage.add_device_used: 'Thêm thiết bị sử dụng',
  KeyLanguage.delete_device: 'Xóa thiết bị',
  KeyLanguage.re_opened: 'Mở lại',
  KeyLanguage.device_use_in_day: 'Thiết bị sử dụng trong ngày',
  // policies
  KeyLanguage.policies_search_secure: 'Tìm kiếm an toàn',
  KeyLanguage.policies_secure_child: 'Bảo vệ trẻ em',
  KeyLanguage.policies_block_web_blacklist: 'Chặn web đen',
  KeyLanguage.policies_block_web_phishing: 'Chặn website giả mạo',
  KeyLanguage.policies_block_web_gamble: 'Chặn web cờ bạc',
  KeyLanguage.policies_anti_scam: 'Chống lừa đảo',

  //pvoil transaction create page
  KeyLanguage.create_transaction: 'Tạo mới giao dịch',
  KeyLanguage.payment_banking: 'Ngân hàng thanh toán',
  KeyLanguage.payment_qrcode: 'Thanh toán bằng QR Code',
  KeyLanguage.next_step: 'Bước tiếp theo',
  KeyLanguage.infomation_user: 'Thông tin tài khoản',
};
